### ISSUE TITLE
app.scss

### ISSUE THREAD

**Issue by Nekzerd** [0xSacul/era-n-est-pas-drole#1]
```scss
@import url('https://fonts.googleapis.com/css2?family=Lexend:wght@300&display=swap');
@import url("https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
@import url("https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap");
@import url('https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap');

html,
body,
#app,
#root,
.main-container {
    width: 100%;
    height: 100%;
    margin: 0;
    padding: 0;
    overflow: hidden;
}

.main-container.dev-background {
    background-image: url("https://cdn.discordapp.com/attachments/667855303840235531/1142870026605580308/ynDIxtd.png");
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
}

@font-face {
    font-family: "Lato";
    src: url("fonts/Lato-Regular.ttf");
    font-style: normal;
}

@font-face {
    font-family: "Rock Salt";
    src: url("fonts/RockSalt-Regular.ttf");
    font-style: normal;
}

@font-face {
    font-family: "Open Sans";
    src: url("fonts/OpenSans-Light.ttf") format("truetype");
    font-style: normal;
}

@font-face {
    font-family: "LuxoraGrotesk";
    src: url("fonts/LuxoraGrotesk-Regular.woff2") format("woff2");
    font-style: normal;
}

@font-face {
    font-family: "Montserrat";
    src: url("fonts/Montserrat-Regular.ttf") format("opentype");
    font-style: normal;
}

@font-face {
    font-family: "Montserrat2";
    src: url("fonts/Montserrat-Regular.ttf") format("opentype");
    font-style: normal;
}

@font-face {
    font-family: "Rage Italic";
    src: url("fonts/rage.ttf") format("truetype");
    font-style: italic;
}

@font-face {
    font-family: "Southera";
    src: url("fonts/Southera.ttf") format("truetype");
    font-style: normal;
}

@font-face {
    font-family: "HavioletaHandwritten";
    src: url("fonts/HavioletaHandwritten.otf") format("truetype");
    font-style: normal;
}

@font-face {
    font-family: "Lexend";
    src: url("fonts/Lexend-VariableFont_wght.ttf") format("truetype");
    font-style: normal;
}

@font-face {
    font-family: "ds-digib";
    src: url("fonts/ds-digib.ttf") format("truetype");
    font-style: normal;
}

@font-face {
    font-family: "Quartz";
    src: url("fonts/Quartz.ttf") format("truetype");
    font-style: normal;
}

@font-face {
    font-family: 'Hacker Argot';
    src: url("fonts/hacka___.ttf") format("truetype");
    font-style: normal;
}

@font-face {
    font-family: 'OCR-A';
    text-transform: uppercase;
    src: url("fonts/OCR-A.ttf") format("truetype");
    font-style: normal;
}

@font-face {
    font-family: "NumberPlate";
    src: url("fonts/UKNumberPlate.ttf") format("truetype");
    font-style: normal;
}

* {
    user-select: none;
    font-family: "Poppins", sans-serif;
}

//for backward compatibility, todo remove this in the future
.d-flex {
    display: flex;
}

.flex-auto {
    flex: auto;
}

.flex-column {
    flex-direction: column;
}

.flex-row {
    flex-direction: row;
}

.justify-content-between {
    justify-content: space-between;
}

.justify-content-center {
    justify-content: center;
}

.justify-content-end {
    justify-content: flex-end;
}

.justify-content-evenly {
    justify-content: space-evenly;
}

.justify-content-around {
    justify-content: space-around;
}

.align-items-center {
    align-items: center;
}

.flex-wrap-reverse {
    flex-wrap: wrap-reverse;
}

.scaleHover:hover {
    scale: 1.05;
}

.scaleHover {
    transition: .3s;
}

* {
    font-family: Lato;
}
```
